image:
  file: .gitpod.Dockerfile

tasks:
  - name: build
    init: ./gradlew build
  - name: docker-compose
    init: >
      cd $GITPOD_REPO_ROOT/.devcontainer && docker-compose pull
    command: >
      cd $GITPOD_REPO_ROOT/.devcontainer && docker-compose up
  - name: hosts
    command: >
      sudo /bin/bash -c 'echo "127.0.0.1    postgres" >> /etc/hosts'

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - richardwillis.vscode-gradle
