version: '3.8'
volumes:
  postgres-data:

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 17-bullseye
        # Options
        INSTALL_MAVEN: "false"
        MAVEN_VERSION: ""
        INSTALL_GRADLE: "false"
        GRADLE_VERSION: ""
        NODE_VERSION: "lts/*"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgresdb

    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
